name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: E2E Tests
        uses: cypress-io/github-action@v3.0.3
        with:
          start: yarn start
          wait-on: 'http://127.0.0.1:5500/src/'
